name: TeamAPI
main: net.acampadas21.teamapi.TeamAPI
version: 0.01a
description: Team creation and management
commands:
  team:
    description: In which team am I
  test:
    description: test command
